// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjxHzt2TM03l1I5YLaXYCmOc1NjrfOl-g',
    appId: '1:833927629311:web:c77b2e8a29a3c7ac78ffca',
    messagingSenderId: '833927629311',
    projectId: 'pesan-1',
    authDomain: 'pesan-1.firebaseapp.com',
    storageBucket: 'pesan-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw3O-KLfRoGoZ1mnK5IpBDKyJKfDBEDNk',
    appId: '1:833927629311:android:1b9f6bbd591b958778ffca',
    messagingSenderId: '833927629311',
    projectId: 'pesan-1',
    storageBucket: 'pesan-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaOTsn-tj_dztY6KP4vA7U2P5sJFJAy7Q',
    appId: '1:833927629311:ios:fb9b7af4de6df1dc78ffca',
    messagingSenderId: '833927629311',
    projectId: 'pesan-1',
    storageBucket: 'pesan-1.appspot.com',
    iosClientId: '833927629311-uuk3up9tq5ekn19ef9vj9lph9lnk1s83.apps.googleusercontent.com',
    iosBundleId: 'com.example.pesan1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaOTsn-tj_dztY6KP4vA7U2P5sJFJAy7Q',
    appId: '1:833927629311:ios:fb9b7af4de6df1dc78ffca',
    messagingSenderId: '833927629311',
    projectId: 'pesan-1',
    storageBucket: 'pesan-1.appspot.com',
    iosClientId: '833927629311-uuk3up9tq5ekn19ef9vj9lph9lnk1s83.apps.googleusercontent.com',
    iosBundleId: 'com.example.pesan1',
  );
}
